Bug 1680011 - Refactor prototype to use AccuWeather as API
htwyford/dynamic-weather-result-extension pull request #3
Opened 2020-12-01 23:34 UTC by htwyford

I split this PR into two commits: the first does the refactor and the second removes the parts of the code that will not be a part of the shipped experiment. I decided to do the refactor first so that the location-fetching and 5-day forecast code are updated to use AccuWeather. This way, we can pull them out of the commit history if we decide to support those features in the future.

The change to AccuWeather necessitates a few design changes. AccuWeather's location APIs return a "location key" once a place is identified. This is a unique identifier, assigned to each place in the world for which AccuWeather could get unique weather data. This key must be passed to their weather APIs to retrieve the weather. I'll call out where its used in an inline comment. Some other things to note:
1. The concept of localities is out. AccuWeather doesn't use them. Instead, `CachedWeatherResult` stores the JSON response from AccuWeather's location API, which contains the location key. The getter for this JSON is `get location()`, so you'll see calls to `data.location.ParameterName` throughout. Similarly, you'll see `data.current.ParameterName`.
2. I changed the design of `isActive`. It now defaults to assuming there's appropriate data in the cache. If there isn't, it refreshes the cache before deciding if the provider is active. This is similar to what we're now doing in UrlbarProviderAutofill, which also fetches data in `isActive`.
3. These two commits on their own used to still build to a working extension. Through Git ineptitude, I managed to break it when splitting it from my patch that implements the new design (bug 1680014). I'll post that patch as a separate PR and then everything should compile nicely when combined.
4. Tests are coming in bug 1680024.

2020-12-01 23:36 UTC, htwyford commented on src/background.js
> +    // instead of AccuWeather's "rank".
AccuWeather returns cities based on a proprietary rank that I think mostly weights population. Basically what this means is that searching for the location "paris" will return Paris, France even if the user lives in Paris, Texas. As a stretch item for this experiment, I'd like to add some simple local matching to filter for cities in the user's country or region.

2020-12-01 23:38 UTC, htwyford commented on src/background.js
> +    const expiryHeader = currentResponse.headers.get("Expiry");
AccuWeather's docs ask that you use the Expiry header to know when to delete cached weather data. Looks like the expiry is 10 minutes in most cases, which is the default value in the `CachedWeatherResult` constructor.

2020-12-01 23:49 UTC, htwyford commented on src/background.js
> +    const locationKey = locationData?.Key;
As I mentioned in the PR description, this is where we pull AccuWeather's location key out of the JSON from their Location API.

2020-12-01 23:51 UTC, htwyford commented
Potentially useful:
General Accuweather docs: https://apidev.accuweather.com/developers/

The text-search location API we're using: https://apidev.accuweather.com/developers/locationsAPIguide#FreeText

The current-weather API we're using: https://apidev.accuweather.com/developers/currentConditionsAPIParameters

2020-12-02 07:34 UTC, 0c0w3 requested changes
Several of my comments are about not hammering AccuWeather with requests in certain cases... I'm not sure to what extent we want this to be production-ready, so let me know if I'm asking too much at this point.

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +      cachedWeatherResults.delete(locationName);
It seems possible that if refreshing the cache happens to take a while, then the user may start multiple queries that trigger a refresh here (since `locationName` is deleted here, so it'll no longer be in the map), but we should only trigger one. In other words, I think we need to keep some kind of state that indicates we're currently refreshing so that we attempt at most one refresh at a time.

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +      if (!locationResponse) {
Similarly here, if there's no location response because AccuWeather didn't have one, we probably shouldn't ask them again for that particular location name. Of course it's possible that the user's internet is down or the server is down, so we probably want some kind of timeout so that we attempt to start asking AccuWeather again, but my point is that we shouldn't hammer them with the same request if the previous one didn't return anything.

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +        return false;
Same here

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +    let data = cachedWeatherResults.get(locationQuery);
It's not a big deal, but `isActive` also gets the location string, so couldn't you keep it in a `_currentLocationString` property instead of recomputing it? If it were just a `map.get` (like the cached result), that would be fine, but `_getLocationString` does some relatively expensive string parsing that isn't necessary to do more than once per query.

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +    const currentUrl = urlObj.toString() + "?" + currentParams.toString();
`url.searchParams` is read-only, meaning you can't assign to it, but the object itself is not, so you can do `url.searchParams.append`, `set`, [etc](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/append). Please do that instead of constructing a string yourself.

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +      return null;
Similar to my comments above, if the response is not OK, we may want a timeout/back-off mechanism before making another request.

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +    const url = urlObj.toString() + "?" + params.toString();
Same here re: `searchParams`

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +    // instead of AccuWeather's "rank".
> Basically what this means is that searching for the location "paris" will return Paris, France even if the user lives in Paris, Texas.

Oh man...

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +
I don't mean to go down a rabbit hole with this, but I would think that "Toronto weather" and "Toronto forecast" would be another common way to phrase it. Can you add a check for `endsWith("weather")` and `"forecast"`, and then assume that everything that came before it is a place name? In the worst case, AccuWeather will just won't return anything for false positives, right?

2020-12-02 07:34 UTC, 0c0w3 commented on src/background.js
> +    return locationData.Country.ID != "US";
🇺🇸

2020-12-02 07:37 UTC, 0c0w3 commented on src/background.js
> +
Also, you want to call `toLocaleLowerCase` on the search string, right?

2020-12-02 07:47 UTC, 0c0w3 commented on src/background.js
> +
> Can you add a check for `endsWith("weather")` and `"forecast"`

Sorry, you're clearly checking `endWith(" forecast")` here. I thought of "weather" and as I was typing my comment I went back and included "forecast", apparently forgetting you're already checking it. But is there a reason you're not also checking "weather"?

2020-12-02 20:06 UTC, htwyford commented on src/background.js
> +      cachedWeatherResults.delete(locationName);
If we block new cache refreshes on old cache refreshes finishing, aren't we wasting the old ones since they will be superceded by the new ones? I added a queryInstance mechanism like we use in in-tree providers, so we bail out if a new query has started. What do you think?

2020-12-02 20:07 UTC, htwyford commented on src/background.js
> +      return null;
I now handle this from the call site in isActive

2020-12-02 20:08 UTC, htwyford commented on src/background.js
> +    return locationData.Country.ID != "US";
The land of the free and the home of inscrutable unit conversions!

2020-12-02 20:21 UTC, htwyford commented on src/background.js
> +      if (!locationResponse) {
I added an invalidLocations `Map`. There's a comment explaining it above

2020-12-03 02:36 UTC, 0c0w3 commented on src/background.js
> +      cachedWeatherResults.delete(locationName);
This is fine, thanks. I'll try to explain what I was getting at, but I think this is fine.

Say the user triggers 3 calls to `isActive` one after the other, and the AccuWeather server is slow, so that call 1 is still ongoing as call 3 starts. If the location in each of the three queries is different, then we don't have a choice but to make 3 different sets of requests to AccuWeather. But if the location is the same -- like it might be as the user is typing a place name, if AccuWeather detects typos/close matches? -- all 3 calls would end up making the same requests unncessarily when really what should happen is that call 1's requests should be allowed to finish and the other 2 should effectively wait for them.

`queryInstance` and `invalidLocations` addresses a lot of that. It's still possible that consecutive `isActive` calls could end up doing the same single request, but with `queryInstance`, it shouldn't be possible for them to do more than one. For example, starting from no cache, if `isActive` call 1 is waiting for a response in `getLocationDataFromQuery` and call 2 starts, then call 2 will also call `getLocationDataFromQuery`, which isn't necessary (as long as the two calls have the same location), but once call 1 gets a response, it will see that its `queryInstance` is old and so it won't continue.

2020-12-03 02:38 UTC, 0c0w3 approved these changes
Thanks! Just check the `searchString.indexOf(" forecast")` -> `" weather"` comment below.

2020-12-03 02:38 UTC, 0c0w3 commented on src/background.js
> +      return searchString.slice(0, searchString.indexOf(" forecast"));
`searchString.indexOf(" weather")`!!  :-)

2020-12-03 16:23 UTC, htwyford commented on src/background.js
> +      cachedWeatherResults.delete(locationName);
> But if the location is the same -- like it might be as the user is typing a place name, if AccuWeather detects typos/close matches? -- all 3 calls would end up making the same requests unncessarily when really what should happen is that call 1's requests should be allowed to finish and the other 2 should effectively wait for them.

Unfortunately, this is not the case. The API looks for exact matches. I'm looking into getting access to their [Autocomplete API](https://apidev.accuweather.com/developers/auto-complete), which will require a separate set of changes.

2020-12-03 17:12 UTC, merged